#!/bin/sh

CLDRCOMMON=~/Work/dev/cldr/source/common
PYTHON=pypy
rm -fr cldrdata
rm -fr cldrflat
mkdir cldrdata
mkdir cldrflat
${PYTHON} python/scripts/cldrimport --hg ${CLDRCOMMON} cldrdata
# No need for -A since going to unflatten immediately
${PYTHON} python/scripts/ldmlflatten -i cldrdata -o cldrflat -a
${PYTHON} python/scripts/ldmlflatten -i cldrflat -o sldr -a -r
