name: Build
on:
  workflow_call:
    outputs:
      artifact_id:
        description: "The artifact uploaded by this build"
        value: ${{ jobs.build.outputs.artifact.id }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.upload.outputs }}
    steps:      
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install 'git+https://github.com/silnrsi/sldrtools'
    - uses: actions/checkout@v3

    - name: Generate unflattened sldr
      run: ldmlflatten -o unflat -i sldr -a -c -g    

    - name: Generate flattened sldr
      run: ldmlflatten -o flat -i sldr -a -A -g

    - uses: actions/upload-artifact@v4
      id: upload
      with:
        name: sldr
        path: |
           flat/
           unflat/
