name: Build
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install 'git+https://github.com/silnrsi/sldrtools'
    - uses: actions/checkout@v3

    - name: Generate unflattened sldr
      run: ldmlflatten -o unflat -i sldr -a -c -g    

    - name: Generate flattened sldr
      run: ldmlflatten -o flat -i sldr -a -A -g

    - uses: actions/upload-artifact@v3
      with:
        name: sldr
        path: |
           flat/
           unflat/
