name: Deploy to server
on:
  workflow_call:
    inputs:
      stage-to:
        required: true
        type: string
      artifact-id:
        required: true
        type: string
    secrets:
      uploader-key:
        required: true
      server-address:
        required: true
      repository-dispatch-pat:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RSYNC_OPTS: -aP --no-p --no-g --no-t --compress --del -e "ssh -o StrictHostKeyChecking=no"
    steps:
    # Install our private key for uploading deliverable
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{secrets.uploader-key}}
    # Download the artefact
    - uses: actions/download-artifact@v4
      with:
        name: sldr
    # Upload results
    - name: Upload flattened SLDR to /ldml-api/data/${{ inputs.stage-to }}
      run: rsync ${{env.RSYNC_OPTS}} --chmod=Dug=rwx flat unflat ${{secrets.server-address}}/sites/s/ldml-api/data/${{ inputs.stage-to }}/

  dispatch:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Trigger langtags rebuild
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.repository-dispatch-pat }}
        repository: silnrsi/langtags
        event-type: sldr-deployed
        client-payload: >- 
          {
            "release": "${{ github.ref_name == 'release' }}"
            "artifact-id": ${{ inputs.artifact-id }}
          }
