name: Deploy to server
on:
  workflow_call:
    inputs:
      stage_to:
        required: true
        type: string
    secrets:
      uploader_key:
        required: true
      server_address:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RSYNC_OPTS: -aP --no-p --no-g --no-t --compress --del -e "ssh -o StrictHostKeyChecking=no"
    steps:
    # Install our private key for uploading deliverable
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{secrets.uploader_key}}
    # Download the artefact
    - uses: actions/download-artifact@v3
      with:
        name: sldr
    # Upload results
    - name: Upload flattened SLDR to /ldml-api/data/${{ inputs.stage }}
      run: rsync ${{env.RSYNC_OPTS}} --chmod=Dug=rwx flat unflat ${{secrets.server_address}}/sites/s/ldml-api/data/${{ inputs.stage }}/

  dispatch:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Trigger langtags rebuild
      uses: actions/github-script@v6
      with:
        script: |
          const octokit = new Octokit({
            auth: '${{ secrets.CROSSREPO_DISPATCH }}'
          })
          await octokit.request('POST /repos/{owner}/{repo}/dispatches', {
            owner: 'silnrsi',
            repo: 'langtags',
            event_type: 'sldr-deployed',
            client_payload: {
              release: '${GITHUB_REF##*/}' == 'release'
            }
          })
