name: Flatten SLDR and publish release branch to production
on:
  push:
    paths:
    - sldr/**
    branches: [ release ]
  pull_request:
    paths:
    - sldr/**
    branches: [ release ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

# Deploy built artefacts to the secrets.UPLOAD_TARGET
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      stage_to: sldr
      artifact_id: ${{ needs.build.outputs.artifact_id }}
    secrets:
      uploader_key: ${{ secrets.UPLOADER_SSH_KEY }}
      server_address: ${{ secrets.UPLOAD_TARGET }}
      repository_dispatch_pat: ${{ secrets.REPO_DISPATCH_TOKEN }}