name: Flatten SLDR and publish release branch to production
on:
  push:
    paths:
    - .github/workflows/**
    - sldr/**
    branches: [ release ]
  pull_request:
    types:
    - closed
    paths:
    - .github/workflows/**
    - sldr/**
    branches: [ release ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

# Deploy built artefacts to the secrets.UPLOAD_TARGET
  deploy:
    needs: build
    if: needs.build.outputs.cache-hit != 'true' && (github.event_name == 'push' || github.event.pull_request.merged == true)
    uses: ./.github/workflows/deploy.yml
    with:
      stage-to: sldr
    secrets:
      uploader-key: ${{ secrets.UPLOADER_SSH_KEY }}
      server-address: ${{ secrets.UPLOAD_TARGET }}
      repository-dispatch-pat: ${{ secrets.REPO_DISPATCH_TOKEN }}
