name: Flatten SLDR and publish release branch to production
on:
  push:
    paths:
    - .github/workflows/**
    - sldr/**
    branches: [ release ]
  pull_request:
    types:
    - closed
    paths:
    - .github/workflows/**
    - sldr/**
    branches: [ release ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

# Deploy built artefacts to the secrets.UPLOAD_TARGET
  deploy:
    needs: build
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      stage-to: sldr
