name: Release SLDR build
on:
  workflow_run:
    workflows: [Flatten SLDR and publish master to staging, Flatten SLDR and publish release branch to production]
    types:
    - completed

jobs:
  release-build:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'release'}}
    steps:
      - id: artifact
        uses: actions/download-artifact@v4
        with:
          name: sldr
      
      - run: >-
          gh release create 
          --generate-notes 
          --target release
          --latest
          --title "Production SLDR data $(date --utc +%G%V%w%H%M)"
          sldr

  prerelease-build:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'release'}}
    steps:
      - id: artifact
        uses: actions/download-artifact@v4
        with:
          name: sldr
      
      - run: >-
          gh release upload staging sldr --clobber
